from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(757, 844)
        MainWindow.setMinimumSize(QtCore.QSize(757, 844))
        MainWindow.setMaximumSize(QtCore.QSize(757, 844))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 761, 851))
        self.stackedWidget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0.273, x2:0, y2:0.222, stop:0 rgba(116, 137, 228, 255), stop:1 rgba(255, 204, 0, 255))")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.Button_Income = QtWidgets.QPushButton(self.home)
        self.Button_Income.setGeometry(QtCore.QRect(140, 330, 211, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_Income.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_Income.setFont(font)
        self.Button_Income.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_Income.setObjectName("Button_Income")
        self.Button_Unrecorded = QtWidgets.QPushButton(self.home)
        self.Button_Unrecorded.setGeometry(QtCore.QRect(140, 550, 461, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_Unrecorded.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_Unrecorded.setFont(font)
        self.Button_Unrecorded.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_Unrecorded.setObjectName("Button_Unrecorded")
        self.Button_prediction = QtWidgets.QPushButton(self.home)
        self.Button_prediction.setGeometry(QtCore.QRect(140, 440, 211, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_prediction.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_prediction.setFont(font)
        self.Button_prediction.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_prediction.setObjectName("Button_prediction")
        self.Button_reporting = QtWidgets.QPushButton(self.home)
        self.Button_reporting.setGeometry(QtCore.QRect(390, 440, 211, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_reporting.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_reporting.setFont(font)
        self.Button_reporting.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_reporting.setObjectName("Button_reporting")
        self.Button_Expense = QtWidgets.QPushButton(self.home)
        self.Button_Expense.setGeometry(QtCore.QRect(390, 330, 211, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_Expense.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_Expense.setFont(font)
        self.Button_Expense.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_Expense.setObjectName("Button_Expense")
        self.AppTitle = QtWidgets.QLabel(self.home)
        self.AppTitle.setEnabled(True)
        self.AppTitle.setGeometry(QtCore.QRect(140, 40, 481, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.AppTitle.setFont(font)
        self.AppTitle.setAutoFillBackground(False)
        self.AppTitle.setStyleSheet("background-color: transparent")
        self.AppTitle.setObjectName("AppTitle")
        self.stackedWidget.addWidget(self.home)
        self.income = QtWidgets.QWidget()
        self.income.setObjectName("income")
        self.Button_back = QtWidgets.QPushButton(self.income)
        self.Button_back.setGeometry(QtCore.QRect(400, 690, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_back.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_back.setFont(font)
        self.Button_back.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_back.setObjectName("Button_back")
        self.Income_edit = QtWidgets.QLineEdit(self.income)
        self.Income_edit.setGeometry(QtCore.QRect(320, 330, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Income_edit.setFont(font)
        self.Income_edit.setStyleSheet("background-color:white")
        self.Income_edit.setObjectName("Income_edit")
        self.Button_prediction_3 = QtWidgets.QPushButton(self.income)
        self.Button_prediction_3.setGeometry(QtCore.QRect(240, 690, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_prediction_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_prediction_3.setFont(font)
        self.Button_prediction_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_prediction_3.setObjectName("Button_prediction_3")
        self.label = QtWidgets.QLabel(self.income)
        self.label.setGeometry(QtCore.QRect(170, 50, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:transparent")
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.income)
        self.label_6.setGeometry(QtCore.QRect(220, 480, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:transparent")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.income)
        self.label_7.setGeometry(QtCore.QRect(190, 320, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:transparent")
        self.label_7.setObjectName("label_7")
        self.Income_category = QtWidgets.QComboBox(self.income)
        self.Income_category.setGeometry(QtCore.QRect(320, 400, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Income_category.setFont(font)
        self.Income_category.setStyleSheet("QComboBox { background-color: white; }")
        self.Income_category.setObjectName("Income_category")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Income_category.addItem("")
        self.Input_instructions = QtWidgets.QLabel(self.income)
        self.Input_instructions.setGeometry(QtCore.QRect(20, 260, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Input_instructions.setFont(font)
        self.Input_instructions.setStyleSheet("background-color:transparent")
        self.Input_instructions.setObjectName("Input_instructions")
        self.label_8 = QtWidgets.QLabel(self.income)
        self.label_8.setGeometry(QtCore.QRect(170, 400, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:transparent")
        self.label_8.setObjectName("label_8")
        self.dateEdit_income = QtWidgets.QDateEdit(self.income)
        self.dateEdit_income.setGeometry(QtCore.QRect(320, 480, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_income.setFont(font)
        self.dateEdit_income.setStyleSheet("background-color:transparent")
        self.dateEdit_income.setObjectName("dateEdit_income")
        self.stackedWidget.addWidget(self.income)
        self.expense = QtWidgets.QWidget()
        self.expense.setObjectName("expense")
        self.Input_instructions_2 = QtWidgets.QLabel(self.expense)
        self.Input_instructions_2.setGeometry(QtCore.QRect(20, 260, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Input_instructions_2.setFont(font)
        self.Input_instructions_2.setStyleSheet("background-color:transparent")
        self.Input_instructions_2.setObjectName("Input_instructions_2")
        self.label_9 = QtWidgets.QLabel(self.expense)
        self.label_9.setGeometry(QtCore.QRect(220, 480, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color:transparent")
        self.label_9.setObjectName("label_9")
        self.expense_category = QtWidgets.QComboBox(self.expense)
        self.expense_category.setGeometry(QtCore.QRect(320, 400, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expense_category.setFont(font)
        self.expense_category.setStyleSheet("QComboBox { background-color: white; }")
        self.expense_category.setObjectName("expense_category")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.expense_category.addItem("")
        self.label_10 = QtWidgets.QLabel(self.expense)
        self.label_10.setGeometry(QtCore.QRect(190, 320, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color:transparent")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.expense)
        self.label_11.setGeometry(QtCore.QRect(170, 400, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color:transparent")
        self.label_11.setObjectName("label_11")
        self.Button_prediction_4 = QtWidgets.QPushButton(self.expense)
        self.Button_prediction_4.setGeometry(QtCore.QRect(240, 690, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_prediction_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_prediction_4.setFont(font)
        self.Button_prediction_4.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_prediction_4.setObjectName("Button_prediction_4")
        self.title_expense = QtWidgets.QLabel(self.expense)
        self.title_expense.setGeometry(QtCore.QRect(170, 50, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title_expense.setFont(font)
        self.title_expense.setStyleSheet("background-color:transparent")
        self.title_expense.setObjectName("title_expense")
        self.Button_back_2 = QtWidgets.QPushButton(self.expense)
        self.Button_back_2.setGeometry(QtCore.QRect(400, 690, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_back_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_back_2.setFont(font)
        self.Button_back_2.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_back_2.setObjectName("Button_back_2")
        self.dateEdit_expense = QtWidgets.QDateEdit(self.expense)
        self.dateEdit_expense.setGeometry(QtCore.QRect(320, 480, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_expense.setFont(font)
        self.dateEdit_expense.setStyleSheet("background-color:transparent")
        self.dateEdit_expense.setObjectName("dateEdit_expense")
        self.expense_edit = QtWidgets.QLineEdit(self.expense)
        self.expense_edit.setGeometry(QtCore.QRect(320, 330, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expense_edit.setFont(font)
        self.expense_edit.setStyleSheet("background-color:white")
        self.expense_edit.setObjectName("expense_edit")
        self.stackedWidget.addWidget(self.expense)
        self.prediction = QtWidgets.QWidget()
        self.prediction.setObjectName("prediction")
        self.title_prediction = QtWidgets.QLabel(self.prediction)
        self.title_prediction.setGeometry(QtCore.QRect(240, 50, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title_prediction.setFont(font)
        self.title_prediction.setStyleSheet("background-color:transparent")
        self.title_prediction.setObjectName("title_prediction")
        self.Button_back_3 = QtWidgets.QPushButton(self.prediction)
        self.Button_back_3.setGeometry(QtCore.QRect(400, 690, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_back_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_back_3.setFont(font)
        self.Button_back_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_back_3.setObjectName("Button_back_3")
        self.Button_prediction_7 = QtWidgets.QPushButton(self.prediction)
        self.Button_prediction_7.setGeometry(QtCore.QRect(240, 690, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_prediction_7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_prediction_7.setFont(font)
        self.Button_prediction_7.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_prediction_7.setObjectName("Button_prediction_7")
        self.stackedWidget.addWidget(self.prediction)
        self.reporting = QtWidgets.QWidget()
        self.reporting.setObjectName("reporting")
        self.title_projecting = QtWidgets.QLabel(self.reporting)
        self.title_projecting.setGeometry(QtCore.QRect(240, 50, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title_projecting.setFont(font)
        self.title_projecting.setStyleSheet("background-color:transparent")
        self.title_projecting.setObjectName("title_projecting")
        self.Button_prediction_15 = QtWidgets.QPushButton(self.reporting)
        self.Button_prediction_15.setGeometry(QtCore.QRect(240, 690, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_prediction_15.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_prediction_15.setFont(font)
        self.Button_prediction_15.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_prediction_15.setObjectName("Button_prediction_15")
        self.Button_back_4 = QtWidgets.QPushButton(self.reporting)
        self.Button_back_4.setGeometry(QtCore.QRect(400, 690, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_back_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_back_4.setFont(font)
        self.Button_back_4.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_back_4.setObjectName("Button_back_4")
        self.stackedWidget.addWidget(self.reporting)
        self.unr = QtWidgets.QWidget()
        self.unr.setObjectName("unr")
        self.Button_back_5 = QtWidgets.QPushButton(self.unr)
        self.Button_back_5.setGeometry(QtCore.QRect(450, 710, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_back_5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Button_back_5.setFont(font)
        self.Button_back_5.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.Button_back_5.setObjectName("Button_back_5")
        self.Fact_edit = QtWidgets.QLineEdit(self.unr)
        self.Fact_edit.setGeometry(QtCore.QRect(320, 390, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Fact_edit.setFont(font)
        self.Fact_edit.setStyleSheet("background-color:white")
        self.Fact_edit.setText("")
        self.Fact_edit.setObjectName("Fact_edit")
        self.Expense_show_label = QtWidgets.QLabel(self.unr)
        self.Expense_show_label.setGeometry(QtCore.QRect(130, 470, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Expense_show_label.setFont(font)
        self.Expense_show_label.setStyleSheet("background-color:transparent")
        self.Expense_show_label.setObjectName("Expense_show_label")
        self.Owed_label = QtWidgets.QLabel(self.unr)
        self.Owed_label.setGeometry(QtCore.QRect(130, 570, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Owed_label.setFont(font)
        self.Owed_label.setStyleSheet("background-color:transparent")
        self.Owed_label.setObjectName("Owed_label")
        self.Owe_label = QtWidgets.QLabel(self.unr)
        self.Owe_label.setGeometry(QtCore.QRect(130, 540, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Owe_label.setFont(font)
        self.Owe_label.setStyleSheet("background-color:transparent")
        self.Owe_label.setObjectName("Owe_label")
        self.label_2 = QtWidgets.QLabel(self.unr)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:transparent")
        self.label_2.setObjectName("label_2")
        self.UNR_label = QtWidgets.QLabel(self.unr)
        self.UNR_label.setGeometry(QtCore.QRect(20, 270, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UNR_label.setFont(font)
        self.UNR_label.setStyleSheet("background-color:transparent")
        self.UNR_label.setObjectName("UNR_label")
        self.Net_debt_label = QtWidgets.QLabel(self.unr)
        self.Net_debt_label.setGeometry(QtCore.QRect(130, 510, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Net_debt_label.setFont(font)
        self.Net_debt_label.setStyleSheet("background-color:transparent")
        self.Net_debt_label.setObjectName("Net_debt_label")
        self.UNR_submit_button = QtWidgets.QPushButton(self.unr)
        self.UNR_submit_button.setGeometry(QtCore.QRect(290, 710, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.UNR_submit_button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UNR_submit_button.setFont(font)
        self.UNR_submit_button.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.UNR_submit_button.setObjectName("UNR_submit_button")
        self.UNR_calculate_button = QtWidgets.QPushButton(self.unr)
        self.UNR_calculate_button.setGeometry(QtCore.QRect(130, 710, 141, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 56, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.UNR_calculate_button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.UNR_calculate_button.setFont(font)
        self.UNR_calculate_button.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(20, 56, 127)")
        self.UNR_calculate_button.setObjectName("UNR_calculate_button")
        self.UNR_label_2 = QtWidgets.QLabel(self.unr)
        self.UNR_label_2.setGeometry(QtCore.QRect(130, 620, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.UNR_label_2.setFont(font)
        self.UNR_label_2.setStyleSheet("background-color:transparent")
        self.UNR_label_2.setObjectName("UNR_label_2")
        self.UNR_formula = QtWidgets.QLabel(self.unr)
        self.UNR_formula.setGeometry(QtCore.QRect(20, 320, 571, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.UNR_formula.setFont(font)
        self.UNR_formula.setStyleSheet("background-color:transparent")
        self.UNR_formula.setObjectName("UNR_formula")
        self.Income_show_label = QtWidgets.QLabel(self.unr)
        self.Income_show_label.setGeometry(QtCore.QRect(130, 420, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Income_show_label.setFont(font)
        self.Income_show_label.setStyleSheet("background-color:transparent")
        self.Income_show_label.setObjectName("Income_show_label")
        self.Fact_label = QtWidgets.QLabel(self.unr)
        self.Fact_label.setGeometry(QtCore.QRect(130, 390, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Fact_label.setFont(font)
        self.Fact_label.setStyleSheet("background-color:transparent")
        self.Fact_label.setObjectName("Fact_label")
        self.UNR_instructions = QtWidgets.QLabel(self.unr)
        self.UNR_instructions.setGeometry(QtCore.QRect(20, 230, 701, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.UNR_instructions.setFont(font)
        self.UNR_instructions.setStyleSheet("background-color:transparent")
        self.UNR_instructions.setObjectName("UNR_instructions")
        self.Income_value_label = QtWidgets.QLabel(self.unr)
        self.Income_value_label.setGeometry(QtCore.QRect(320, 420, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Income_value_label.setFont(font)
        self.Income_value_label.setStyleSheet("background-color:transparent")
        self.Income_value_label.setText("")
        self.Income_value_label.setObjectName("Income_value_label")
        self.Net_debt_value_label = QtWidgets.QLabel(self.unr)
        self.Net_debt_value_label.setGeometry(QtCore.QRect(320, 510, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Net_debt_value_label.setFont(font)
        self.Net_debt_value_label.setStyleSheet("background-color:transparent")
        self.Net_debt_value_label.setText("")
        self.Net_debt_value_label.setObjectName("Net_debt_value_label")
        self.Owed_label_value_label = QtWidgets.QLabel(self.unr)
        self.Owed_label_value_label.setGeometry(QtCore.QRect(320, 570, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Owed_label_value_label.setFont(font)
        self.Owed_label_value_label.setStyleSheet("background-color:transparent")
        self.Owed_label_value_label.setText("")
        self.Owed_label_value_label.setObjectName("Owed_label_value_label")
        self.Owe_label_value_label = QtWidgets.QLabel(self.unr)
        self.Owe_label_value_label.setGeometry(QtCore.QRect(320, 540, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Owe_label_value_label.setFont(font)
        self.Owe_label_value_label.setStyleSheet("background-color:transparent")
        self.Owe_label_value_label.setText("")
        self.Owe_label_value_label.setObjectName("Owe_label_value_label")
        self.Expense_show_value_label = QtWidgets.QLabel(self.unr)
        self.Expense_show_value_label.setGeometry(QtCore.QRect(320, 470, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Expense_show_value_label.setFont(font)
        self.Expense_show_value_label.setStyleSheet("background-color:transparent")
        self.Expense_show_value_label.setText("")
        self.Expense_show_value_label.setObjectName("Expense_show_value_label")
        self.stackedWidget.addWidget(self.unr)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 36))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionIncome_input = QtWidgets.QAction(MainWindow)
        self.actionIncome_input.setObjectName("actionIncome_input")
        self.actionExpense_input = QtWidgets.QAction(MainWindow)
        self.actionExpense_input.setObjectName("actionExpense_input")
        self.actionPrediction = QtWidgets.QAction(MainWindow)
        self.actionPrediction.setObjectName("actionPrediction")
        self.actionReporting = QtWidgets.QAction(MainWindow)
        self.actionReporting.setObjectName("actionReporting")
        self.actionUnrecorded_transactions = QtWidgets.QAction(MainWindow)
        self.actionUnrecorded_transactions.setObjectName("actionUnrecorded_transactions")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionIncome_input)
        self.menuMenu.addAction(self.actionExpense_input)
        self.menuMenu.addAction(self.actionPrediction)
        self.menuMenu.addAction(self.actionReporting)
        self.menuMenu.addAction(self.actionUnrecorded_transactions)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Income.setText(_translate("MainWindow", "Income Input"))
        self.Button_Unrecorded.setText(_translate("MainWindow", "Unrecorded transactions"))
        self.Button_prediction.setText(_translate("MainWindow", "Prediction"))
        self.Button_reporting.setText(_translate("MainWindow", "Reporting"))
        self.Button_Expense.setText(_translate("MainWindow", "Expense Input"))
        self.AppTitle.setText(_translate("MainWindow", "Personal Finance"))
        self.Button_back.setText(_translate("MainWindow", "Back"))
        self.Button_prediction_3.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "Income Input"))
        self.label_6.setText(_translate("MainWindow", "Date:"))
        self.label_7.setText(_translate("MainWindow", "Amount:"))
        self.Income_category.setItemText(0, _translate("MainWindow", "Choose category"))
        self.Income_category.setItemText(1, _translate("MainWindow", "1-Groceries"))
        self.Income_category.setItemText(2, _translate("MainWindow", "2-Rent"))
        self.Income_category.setItemText(3, _translate("MainWindow", "3-Clothing"))
        self.Income_category.setItemText(4, _translate("MainWindow", "4-Entertainment"))
        self.Income_category.setItemText(5, _translate("MainWindow", "5-Dining out"))
        self.Income_category.setItemText(6, _translate("MainWindow", "6-Electronics"))
        self.Income_category.setItemText(7, _translate("MainWindow", "7-Insurance"))
        self.Income_category.setItemText(8, _translate("MainWindow", "8-Medical expenses"))
        self.Income_category.setItemText(9, _translate("MainWindow", "9-Taxes"))
        self.Income_category.setItemText(10, _translate("MainWindow", "10-Transportation"))
        self.Income_category.setItemText(11, _translate("MainWindow", "11-Utilities"))
        self.Input_instructions.setText(_translate("MainWindow", "Input the amount of income in euros and select it\'s category and date."))
        self.label_8.setText(_translate("MainWindow", "Category:"))
        self.Input_instructions_2.setText(_translate("MainWindow", "Input the expense amount in euros and select it\'s category and date."))
        self.label_9.setText(_translate("MainWindow", "Date:"))
        self.expense_category.setItemText(0, _translate("MainWindow", "Choose category"))
        self.expense_category.setItemText(1, _translate("MainWindow", "1-Groceries"))
        self.expense_category.setItemText(2, _translate("MainWindow", "2-Rent"))
        self.expense_category.setItemText(3, _translate("MainWindow", "3-Clothing"))
        self.expense_category.setItemText(4, _translate("MainWindow", "4-Entertainment"))
        self.expense_category.setItemText(5, _translate("MainWindow", "5-Dining out"))
        self.expense_category.setItemText(6, _translate("MainWindow", "6-Electronics"))
        self.expense_category.setItemText(7, _translate("MainWindow", "7-Insurance"))
        self.expense_category.setItemText(8, _translate("MainWindow", "8-Medical expenses"))
        self.expense_category.setItemText(9, _translate("MainWindow", "9-Taxes"))
        self.expense_category.setItemText(10, _translate("MainWindow", "10-Transportation"))
        self.expense_category.setItemText(11, _translate("MainWindow", "11-Utilities"))
        self.label_10.setText(_translate("MainWindow", "Amount:"))
        self.label_11.setText(_translate("MainWindow", "Category:"))
        self.Button_prediction_4.setText(_translate("MainWindow", "Submit"))
        self.title_expense.setText(_translate("MainWindow", "Expense Input"))
        self.Button_back_2.setText(_translate("MainWindow", "Back"))
        self.title_prediction.setText(_translate("MainWindow", "Prediction"))
        self.Button_back_3.setText(_translate("MainWindow", "Back"))
        self.Button_prediction_7.setText(_translate("MainWindow", "Download"))
        self.title_projecting.setText(_translate("MainWindow", "Projecting"))
        self.Button_prediction_15.setText(_translate("MainWindow", "Download"))
        self.Button_back_4.setText(_translate("MainWindow", "Back"))
        self.Button_back_5.setText(_translate("MainWindow", "Back"))
        self.Expense_show_label.setText(_translate("MainWindow", "Expenses:"))
        self.Owed_label.setText(_translate("MainWindow", "You are Owed: "))
        self.Owe_label.setText(_translate("MainWindow", "You Owe: "))
        self.label_2.setText(_translate("MainWindow", "Unrecorded Transactions"))
        self.UNR_label.setText(_translate("MainWindow", "Unrecorded (UNR) amount is calculated as following:"))
        self.Net_debt_label.setText(_translate("MainWindow", "Net Debt:  "))
        self.UNR_submit_button.setText(_translate("MainWindow", "Submit"))
        self.UNR_calculate_button.setText(_translate("MainWindow", "Calculate"))
        self.UNR_label_2.setText(_translate("MainWindow", "UNR Amount: "))
        self.UNR_formula.setText(_translate("MainWindow", "UNR = Incomes - Expenses + Net Debt - Fact Balance"))
        self.Income_show_label.setText(_translate("MainWindow", "Income: "))
        self.Fact_label.setText(_translate("MainWindow", "Fact Balance:"))
        self.UNR_instructions.setText(_translate("MainWindow", "Input the Fact Balance in euros to calculate the Unrecorded amount."))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionIncome_input.setText(_translate("MainWindow", "Income input"))
        self.actionExpense_input.setText(_translate("MainWindow", "Expense input"))
        self.actionPrediction.setText(_translate("MainWindow", "Prediction"))
        self.actionReporting.setText(_translate("MainWindow", "Reporting"))
        self.actionUnrecorded_transactions.setText(_translate("MainWindow", "Unrecorded transactions"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())